In [1]:
import pandas as pd
import matplotlib.pyplot as plt

#ціни акцій типу 123.45678 показувати з дробами, а великі обсяги - без
pd.set_option('display.float_format', 
              lambda x: '{:,.1f}'.format(x) if abs(x) >= 1000 or abs(x) == 0 else '{:.8f}'.format(x))


path = r"C:/Users/stepa/Desktop/АДІС/KP_ADIS_Macroeconomic_analysis/ADIS_Project_source_datasets/"
file_stocks = "world_stock_prices_dataset.csv"
file_gdp = "world_gdp_by_country.csv"
file_crypto = "crypto_historical_data.csv"
file_inflation = "global_inflation_data.csv"
file_unemployment = "global_unemployment_data.csv"
file_real_interest = "real_interest_rate_by_country.csv"


df_stocks = pd.read_csv(path + file_stocks, sep = ",", encoding = "cp1252")
df_gdp = pd.read_csv(path + file_gdp, sep = ",", encoding = "cp1252")
df_crypto = pd.read_csv(path + file_crypto, sep = ",", encoding = "cp1252")
#після df_inflation.head() було виявлено що підібраний cp1252 невірний - змінено енкодинг
df_inflation = pd.read_csv(path + file_inflation, sep = ",", encoding = "utf-8-sig") 
df_unemployment = pd.read_csv(path + file_unemployment, sep = ",", encoding = "cp1252")
df_real_interest = pd.read_csv(path + file_real_interest, sep = ",", encoding = "cp1252")

<h2>Обробка датасету df_stocks</h2>

In [2]:
df_stocks.head()

,Date,Open,High,Low,Close,Volume,Brand_Name,Ticker,Industry_Tag,Country,Dividends,Stock Splits,Capital Gains
0,2025-07-03 00:00:00-04:00,6.63000011,6.73999977,6.61499977,6.63999987,"4,209,664.0",peloton,PTON,fitness,usa,0.0,0.0,NaN
1,2025-07-03 00:00:00-04:00,106.75000000,108.37000275,106.33010101,107.33999634,"560,190.0",crocs,CROX,footwear,usa,0.0,0.0,NaN
2,2025-07-03 00:00:00-04:00,122.62999725,123.05000305,121.55000305,121.93000031,"36,600.0",adidas,ADDYY,apparel,germany,0.0,0.0,NaN
3,2025-07-03 00:00:00-04:00,221.70500183,224.00999451,221.36000061,223.41000366,"29,295,154.0",amazon,AMZN,e-commerce,usa,0.0,0.0,NaN
4,2025-07-03 00:00:00-04:00,212.14500427,214.64999390,211.81010437,213.55000305,"34,697,317.0",apple,AAPL,technology,usa,0.0,0.0,NaN

In [3]:
df_stocks = df_stocks.rename(columns={
    "Date": "date",
    "Open": "open",
    "High": "high",
    "Low": "low",
    "Close": "close",
    "Volume": "volume",
    "Brand_Name": "brand_name",
    "Ticker": "ticker",
    "Industry_Tag": "industry_tag",
    "Country": "country",
    "Dividends": "dividends",
    "Stock Splits": "stock_splits",
    "Capital Gains": "capital_gains"
})

#df_stocks[['open', 'high', 'low', 'close']].iloc[:5].to_string(float_format='{:0.15f}'.format)

#df_stocks = df_stocks.style.format({
#    'open': '{:.15f}',
#    'high': '{:.15f}',
#    'low': '{:.15f}',
#    'close': '{:.15f}',
#    'volume': '{:,.0f}'
#}) 

df_stocks["date"] = pd.to_datetime(df_stocks["date"].astype(str), utc=True)

df_stocks.head()

,date,open,high,low,close,volume,brand_name,ticker,industry_tag,country,dividends,stock_splits,capital_gains
0,2025-07-03 04:00:00+00:00,6.63000011,6.73999977,6.61499977,6.63999987,"4,209,664.0",peloton,PTON,fitness,usa,0.0,0.0,NaN
1,2025-07-03 04:00:00+00:00,106.75000000,108.37000275,106.33010101,107.33999634,"560,190.0",crocs,CROX,footwear,usa,0.0,0.0,NaN
2,2025-07-03 04:00:00+00:00,122.62999725,123.05000305,121.55000305,121.93000031,"36,600.0",adidas,ADDYY,apparel,germany,0.0,0.0,NaN
3,2025-07-03 04:00:00+00:00,221.70500183,224.00999451,221.36000061,223.41000366,"29,295,154.0",amazon,AMZN,e-commerce,usa,0.0,0.0,NaN
4,2025-07-03 04:00:00+00:00,212.14500427,214.64999390,211.81010437,213.55000305,"34,697,317.0",apple,AAPL,technology,usa,0.0,0.0,NaN

In [4]:
df_stocks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 310122 entries, 0 to 310121
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   date           310122 non-null  datetime64[ns, UTC]
 1   open           310122 non-null  float64
 2   high           310122 non-null  float64
 3   low            310122 non-null  float64
 4   close          310122 non-null  float64
 5   volume         310122 non-null  float64
 6   brand_name     310122 non-null  object
 7   ticker         310122 non-null  object
 8   industry_tag   310122 non-null  object
 9   country        310122 non-null  object
 10  dividends      310122 non-null  float64
 11  stock_splits   310122 non-null  float64
 12  capital_gains  2 non-null       float64
dtypes: datetime64[ns, UTC](1), float64(8), object(4)
memory usage: 30.8+ MB

In [5]:
#перегляд детальної інформації про датафрейм
df_stocks.describe(include = "all")

,date,open,high,low,close,volume,brand_name,ticker,industry_tag,country,dividends,stock_splits,capital_gains
count,310122,"310,122.0","310,122.0","310,122.0","310,122.0","310,122.0",310122,310122,310122,310122,"310,122.0","310,122.0",2.00000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,62,62,23,7,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,marriott,MAR,technology,usa,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,6471,6471,66957,243606,NaN,NaN,NaN
mean,2014-03-28 01:09:53.139474432+00:00,76.32543132,77.19801135,75.43458576,76.33803235,"22,709,366.0",NaN,NaN,NaN,NaN,0.00364312,0.00087453,0.0
min,2000-01-03 05:00:00+00:00,0.0,0.0,0.0,0.19886118,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0
25%,2008-05-01 04:00:00+00:00,15.93249989,16.16316476,15.71032344,15.93999958,"1,379,050.0",NaN,NaN,NaN,NaN,0.0,0.0,0.0
50%,2014-10-24 04:00:00+00:00,35.40811974,35.80986892,34.98246884,35.40754700,"4,591,641.5",NaN,NaN,NaN,NaN,0.0,0.0,0.0
75%,2020-08-18 04:00:00+00:00,83.99669130,84.91465640,83.08860945,84.00000000,"12,128,600.0",NaN,NaN,NaN,NaN,0.0,0.0,0.0
max,2025-07-03 04:00:00+00:00,"3,445.6","3,463.1","3,370.0","3,427.6","7,421,640,800.0",NaN,NaN,NaN,NaN,15.00000000,50.00000000,0.0
std,NaN,141.68407014,143.22410924,140.06361661,141.67912892,"85,657,437.8",NaN,NaN,NaN,NaN,0.06990542,0.11543440,0.0

In [6]:
#видалення колонки capital_gains, оскліьки колонка майже повністю порожня(окрім 2 знаечнь)
del df_stocks["capital_gains"]

In [7]:
df_stocks.head()

,date,open,high,low,close,volume,brand_name,ticker,industry_tag,country,dividends,stock_splits
0,2025-07-03 04:00:00+00:00,6.63000011,6.73999977,6.61499977,6.63999987,"4,209,664.0",peloton,PTON,fitness,usa,0.0,0.0
1,2025-07-03 04:00:00+00:00,106.75000000,108.37000275,106.33010101,107.33999634,"560,190.0",crocs,CROX,footwear,usa,0.0,0.0
2,2025-07-03 04:00:00+00:00,122.62999725,123.05000305,121.55000305,121.93000031,"36,600.0",adidas,ADDYY,apparel,germany,0.0,0.0
3,2025-07-03 04:00:00+00:00,221.70500183,224.00999451,221.36000061,223.41000366,"29,295,154.0",amazon,AMZN,e-commerce,usa,0.0,0.0
4,2025-07-03 04:00:00+00:00,212.14500427,214.64999390,211.81010437,213.55000305,"34,697,317.0",apple,AAPL,technology,usa,0.0,0.0

In [8]:
#підрахунок відсутніх значень
missing_data_stocks = df_stocks.isnull()

for column in missing_data_stocks.columns.values.tolist():
    print(column)
    print(missing_data_stocks[column].value_counts())
    print("")

missing_percent_stocks = df_stocks.isna().mean() * 100
print(missing_percent_stocks)

date
date
False    310122
Name: count, dtype: int64

open
open
False    310122
Name: count, dtype: int64

high
high
False    310122
Name: count, dtype: int64

low
low
False    310122
Name: count, dtype: int64

close
close
False    310122
Name: count, dtype: int64

volume
volume
False    310122
Name: count, dtype: int64

brand_name
brand_name
False    310122
Name: count, dtype: int64

ticker
ticker
False    310122
Name: count, dtype: int64

industry_tag
industry_tag
False    310122
Name: count, dtype: int64

country
country
False    310122
Name: count, dtype: int64

dividends
dividends
False    310122
Name: count, dtype: int64

stock_splits
stock_splits
False    310122
Name: count, dtype: int64

date           0.0
open           0.0
high           0.0
low            0.0
close          0.0
volume         0.0
brand_name     0.0
ticker         0.0
industry_tag   0.0
country        0.0
dividends      0.0
stock_splits   0.0
dtype: float64

In [9]:
#перевірка на дублікати
duplicates = df_stocks[df_stocks.duplicated(subset=['date', 'ticker'], keep=False)]
print("Кількість дублікатів по df_stocks date + ticker:", len(duplicates))
if len(duplicates) > 0:
    print(duplicates.head())

Кількість дублікатів по df_stocks date + ticker: 7354
                       date         open         high          low  \
0 2025-07-03 04:00:00+00:00   6.63000011   6.73999977   6.61499977
1 2025-07-03 04:00:00+00:00 106.75000000 108.37000275 106.33010101
3 2025-07-03 04:00:00+00:00 221.70500183 224.00999451 221.36000061
4 2025-07-03 04:00:00+00:00 212.14500427 214.64999390 211.81010437
5 2025-07-03 04:00:00+00:00  76.26499939  77.02999878  75.58000183

         close       volume brand_name ticker industry_tag country  dividends  \
0   6.63999987  4,209,664.0    peloton   PTON      fitness     usa        0.0
1 107.33999634    560,190.0      crocs   CROX     footwear     usa        0.0
3 223.41000366 29,295,154.0     amazon   AMZN   e-commerce     usa        0.0
4 213.55000305 34,697,317.0      apple   AAPL   technology     usa        0.0
5  76.38999939 11,545,304.0       nike    NKE      apparel     usa        0.0

   stock_splits
0           0.0
1           0.0
3           0.0
4           0.0
5           0.0

In [10]:
#очищення від дублікатів
df_stocks = (
    df_stocks
    .sort_values('volume', ascending=False)
    .drop_duplicates(subset=['date', 'ticker'], keep='first')
)

#повторна перевірка на дублікати
duplicates = df_stocks[df_stocks.duplicated(subset=['date', 'ticker'], keep=False)]
print("Кількість дублікатів по df_stocks date + ticker:", len(duplicates))
if len(duplicates) > 0:
    print(duplicates.head())

Кількість дублікатів по df_stocks date + ticker: 0

In [11]:
#розрахунок денної прибутковості (дохідності) daily_return
#сортування за ticker та date для коректного pct_change()
df_stocks = df_stocks.sort_values(["ticker", "date"])

#pct_change() рахує % зміни ціни close відносно попереднього дня в межах кожного ticker
df_stocks["daily_return"] = df_stocks.groupby("ticker")["close"].pct_change()

df_stocks.head()

,date,open,high,low,close,volume,brand_name,ticker,industry_tag,country,dividends,stock_splits,daily_return
310097,2000-01-03 05:00:00+00:00,0.79479960,0.85258569,0.77064283,0.84832299,"535,796,800.0",apple,AAPL,technology,usa,0.0,0.0,NaN
310056,2000-01-04 05:00:00+00:00,0.82037722,0.83837596,0.76685383,0.77680087,"512,377,600.0",apple,AAPL,technology,usa,0.0,0.0,-0.08431001
310022,2000-01-05 05:00:00+00:00,0.78627337,0.83790227,0.78058984,0.78816789,"778,321,600.0",apple,AAPL,technology,usa,0.0,0.0,0.01463312
309992,2000-01-06 05:00:00+00:00,0.80427320,0.81090402,0.71996135,0.71996135,"767,972,800.0",apple,AAPL,technology,usa,0.0,0.0,-0.08653810
309979,2000-01-07 05:00:00+00:00,0.73132902,0.76543283,0.72375096,0.75406486,"460,734,400.0",apple,AAPL,technology,usa,0.0,0.0,0.04736853

In [12]:
df_stocks.tail()

,date,open,high,low,close,volume,brand_name,ticker,industry_tag,country,dividends,stock_splits,daily_return
385,2025-06-27 04:00:00+00:00,76.84999847,78.43000031,76.55999756,78.37999725,"3,411,400.0",zoom video communications,ZM,technology,usa,0.0,0.0,0.01845112
231,2025-06-30 04:00:00+00:00,78.44999695,78.48500061,77.25000000,77.98000336,"3,626,300.0",zoom video communications,ZM,technology,usa,0.0,0.0,-0.00510326
206,2025-07-01 04:00:00+00:00,77.79000092,78.17500305,76.87000275,77.56999969,"3,051,600.0",zoom video communications,ZM,technology,usa,0.0,0.0,-0.00525781
116,2025-07-02 04:00:00+00:00,77.09999847,77.69999695,76.66999817,77.58999634,"2,597,000.0",zoom video communications,ZM,technology,usa,0.0,0.0,0.00025779
92,2025-07-03 04:00:00+00:00,77.59999847,79.82499695,77.41000366,78.58000183,"2,889,400.0",zoom video communications,ZM,technology,usa,0.0,0.0,0.01275945

In [13]:
df_stocks.describe(include = "all")

,date,open,high,low,close,volume,brand_name,ticker,industry_tag,country,dividends,stock_splits,daily_return
count,306445,"306,445.0","306,445.0","306,445.0","306,445.0","306,445.0",306445,306445,306445,306445,"306,445.0","306,445.0","306,383.0"
unique,NaN,NaN,NaN,NaN,NaN,NaN,62,62,23,7,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,apple,AAPL,technology,usa,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,6408,6408,66162,240677,NaN,NaN,NaN
mean,2014-02-09 05:39:50.840770816+00:00,75.11080590,75.96960694,74.23307230,75.12262087,"22,814,362.0",NaN,NaN,NaN,NaN,0.00368027,0.00088502,0.00073397
min,2000-01-03 05:00:00+00:00,0.0,0.0,0.0,0.19886118,0.0,NaN,NaN,NaN,NaN,0.0,0.0,-0.98010434
25%,2008-04-02 04:00:00+00:00,15.81570180,16.03972791,15.60000038,15.82261562,"1,376,000.0",NaN,NaN,NaN,NaN,0.0,0.0,-0.00956865
50%,2014-09-03 04:00:00+00:00,35.01982334,35.43094982,34.59040815,35.03618240,"4,597,200.0",NaN,NaN,NaN,NaN,0.0,0.0,0.00029956
75%,2020-06-10 04:00:00+00:00,82.28341202,83.17360745,81.41999817,82.31197357,"12,156,800.0",NaN,NaN,NaN,NaN,0.0,0.0,0.01071703
max,2025-07-03 04:00:00+00:00,"3,445.6","3,463.1","3,370.0","3,427.6","7,421,640,800.0",NaN,NaN,NaN,NaN,15.00000000,50.00000000,0.85703184
std,NaN,140.29716452,141.82631866,138.69028044,140.29199055,"86,065,183.8",NaN,NaN,NaN,NaN,0.07027978,0.11612484,0.02539915

<p>daily_return має 62 пропуски і в нас є 62 унікальних значення по ticker, відповідно це рівно 62 перші дні(для яких неможливо розрахувати daily_return) для кожного ticker, по одному першому дню для кожного ticker</p>

<p>Унікальних назв країн в df_stocks - 7</p>

<h2>Обробка датасету df_gdp</h2>

In [14]:
df_gdp.head()

,Country,Country Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"2,727,932,961.0","2,791,061,453.0","2,963,128,492.0","2,983,798,883.0","3,092,178,771.0","3,276,187,709.0","3,395,793,855.0","2,610,038,939.0","3,126,019,385.0",NaN
1,Africa Eastern and Southern,AFE,"21,125,015,452.0","21,616,228,139.0","23,506,279,900.0","28,048,360,188.0","25,920,665,260.0","29,472,103,270.0","32,014,368,121.0","33,269,509,510.0",...,"985,987,130,727.0","1,006,526,390,113.0","927,348,469,903.0","885,176,429,224.0","1,021,043,200,767.0","1,007,196,197,587.0","1,000,834,077,089.0","927,593,321,648.0","1,081,998,139,192.0","1,169,483,734,191.0"
2,Afghanistan,AFG,"537,777,811.1","548,888,895.6","546,666,677.8","751,111,191.1","800,000,044.4","1,006,666,638.0","1,399,999,967.0","1,673,333,418.0",...,"20,564,485,419.0","20,550,582,747.0","19,998,143,636.0","18,019,554,403.0","18,896,353,156.0","18,418,860,354.0","18,904,502,222.0","20,143,451,706.0","14,583,135,237.0",NaN
3,Africa Western and Central,AFW,"10,447,637,853.0","11,173,212,080.0","11,990,534,018.0","12,727,688,165.0","13,898,109,284.0","14,929,792,388.0","15,910,837,742.0","14,510,579,889.0",...,"833,948,054,767.0","894,322,482,190.0","768,644,740,597.0","691,363,412,188.0","684,898,755,571.0","767,025,741,475.0","822,538,393,591.0","786,460,035,395.0","844,459,722,153.0","877,863,284,874.0"
4,Angola,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"133,401,582,620.0","137,244,439,121.0","87,219,300,385.0","49,840,491,178.0","68,972,769,396.0","77,792,944,472.0","69,309,110,146.0","50,241,368,244.0","65,685,435,100.0","106,713,618,735.0"

In [15]:
df_gdp = df_gdp.rename(columns={
    "Country": "country",
    "Country Code": "country_code"
})

#Перетворення wide-формату в long
#melt метод pandas перетворює таблицю з wide у long-формат
df_gdp = df_gdp.melt(
    id_vars=["country", "country_code"], #стовпці, які залишаються без змін (не перетворюються в рядки)
    var_name="year", #назва нового стовпця, куди потраплять назви старих стовпців (роки)
    value_name="gdp_value" #назва нового стовпця, куди потраплять значення з тих стовпців-років
)

df_gdp

                           country country_code  year         gdp_value
0                            Aruba          ABW  1960               NaN
1      Africa Eastern and Southern          AFE  1960  21,125,015,452.0
2                      Afghanistan          AFG  1960     537,777,811.1
3       Africa Western and Central          AFW  1960  10,447,637,853.0
4                           Angola          AGO  1960               NaN
...                            ...          ...   ...               ...
16753                       Kosovo          XKX  2022   9,429,156,202.0
16754                  Yemen, Rep.          YEM  2022               NaN
16755                 South Africa          ZAF  2022 405,869,718,462.0
16756                       Zambia          ZMB  2022  29,784,454,056.0
16757                     Zimbabwe          ZWE  2022  20,678,055,598.0

[16758 rows x 4 columns]

In [16]:
df_gdp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16758 entries, 0 to 16757
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   country       16758 non-null  object
 1   country_code  16758 non-null  object
 2   year          16758 non-null  object
 3   gdp_value     13365 non-null  float64
dtypes: float64(1), object(3)
memory usage: 523.8+ KB

In [17]:
df_gdp["year"] = pd.to_datetime(df_gdp["year"].astype(str), utc=True)

In [18]:
df_gdp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16758 entries, 0 to 16757
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   country       16758 non-null  object
 1   country_code  16758 non-null  object
 2   year          16758 non-null  datetime64[ns, UTC]
 3   gdp_value     13365 non-null  float64
dtypes: datetime64[ns, UTC](1), float64(1), object(2)
memory usage: 523.8+ KB

In [19]:
df_gdp.head()

,country,country_code,year,gdp_value
0,Aruba,ABW,1960-01-01 00:00:00+00:00,NaN
1,Africa Eastern and Southern,AFE,1960-01-01 00:00:00+00:00,"21,125,015,452.0"
2,Afghanistan,AFG,1960-01-01 00:00:00+00:00,"537,777,811.1"
3,Africa Western and Central,AFW,1960-01-01 00:00:00+00:00,"10,447,637,853.0"
4,Angola,AGO,1960-01-01 00:00:00+00:00,NaN

In [20]:
#перегляд детальної інформації про датафрейм
df_gdp.describe(include = "all")

,country,country_code,year,gdp_value
count,16758,16758,16758,"13,365.0"
unique,266,266,NaN,NaN
top,Aruba,ABW,NaN,NaN
freq,63,63,NaN,NaN
mean,NaN,NaN,1991-01-01 03:02:51.428571392+00:00,"1,206,984,696,897.4"
min,NaN,NaN,1960-01-01 00:00:00+00:00,"8,824,746.2"
25%,NaN,NaN,1975-01-01 00:00:00+00:00,"2,523,471,602.0"
50%,NaN,NaN,1991-01-01 00:00:00+00:00,"18,427,777,778.0"
75%,NaN,NaN,2007-01-01 00:00:00+00:00,"224,383,544,087.0"
max,NaN,NaN,2022-01-01 00:00:00+00:00,"100,562,011,134,034.0"
std,NaN,NaN,NaN,"5,412,747,918,971.2"

In [21]:
# Знаходимо індекс рядка з максимальним gdp_value
idx_max = df_gdp["gdp_value"].idxmax()
# Отримуємо назву країни за цим індексом
country_max = df_gdp.loc[idx_max, "country"]
print(country_max)

World

In [22]:
#видалення рядку з країною World(підсумковий рядок)
df_gdp = df_gdp.drop(idx_max)
df_gdp.describe(include = "all")

,country,country_code,year,gdp_value
count,16757,16757,16757,"13,364.0"
unique,266,266,NaN,NaN
top,Aruba,ABW,NaN,NaN
freq,63,63,NaN,NaN
mean,NaN,NaN,1990-12-31 10:49:50.081756800+00:00,"1,199,550,169,328.0"
min,NaN,NaN,1960-01-01 00:00:00+00:00,"8,824,746.2"
25%,NaN,NaN,1975-01-01 00:00:00+00:00,"2,521,728,304.5"
50%,NaN,NaN,1991-01-01 00:00:00+00:00,"18,427,123,397.5"
75%,NaN,NaN,2007-01-01 00:00:00+00:00,"224,195,320,949.8"
max,NaN,NaN,2022-01-01 00:00:00+00:00,"96,882,397,612,409.0"
std,NaN,NaN,NaN,"5,344,273,969,233.9"

In [23]:
df_gdp.sort_values("gdp_value", ascending=False)

,country,country_code,year,gdp_value
16485,World,WLD,2021-01-01 00:00:00+00:00,"96,882,397,612,409.0"
15953,World,WLD,2019-01-01 00:00:00+00:00,"87,728,102,156,403.0"
15687,World,WLD,2018-01-01 00:00:00+00:00,"86,502,223,934,428.0"
16219,World,WLD,2020-01-01 00:00:00+00:00,"85,215,150,558,552.0"
15421,World,WLD,2017-01-01 00:00:00+00:00,"81,442,048,665,488.0"
...,...,...,...,...
16731,Tonga,TON,2022-01-01 00:00:00+00:00,NaN
16746,"Venezuela, RB",VEN,2022-01-01 00:00:00+00:00,NaN
16747,British Virgin Islands,VGB,2022-01-01 00:00:00+00:00,NaN
16748,Virgin Islands (U.S.),VIR,2022-01-01 00:00:00+00:00,NaN
16754,"Yemen, Rep.",YEM,2022-01-01 00:00:00+00:00,NaN

In [24]:
#видалення рядків де підсумкові значення World за кожен рік
df_gdp = df_gdp[df_gdp["country"] != "World"]
df_gdp.sort_values("gdp_value", ascending=False).head(30)

,country,country_code,year,gdp_value
16587,High income,HIC,2022-01-01 00:00:00+00:00,"61,535,768,880,817.0"
16321,High income,HIC,2021-01-01 00:00:00+00:00,"60,016,712,305,060.0"
16673,OECD members,OED,2022-01-01 00:00:00+00:00,"59,596,537,275,134.0"
16407,OECD members,OED,2021-01-01 00:00:00+00:00,"58,363,931,312,919.0"
16690,Post-demographic dividend,PST,2022-01-01 00:00:00+00:00,"56,013,534,785,820.0"
15789,High income,HIC,2019-01-01 00:00:00+00:00,"55,315,474,922,573.0"
16424,Post-demographic dividend,PST,2021-01-01 00:00:00+00:00,"55,090,863,284,052.0"
15523,High income,HIC,2018-01-01 00:00:00+00:00,"54,839,704,976,037.0"
16055,High income,HIC,2020-01-01 00:00:00+00:00,"53,937,976,780,898.0"
15875,OECD members,OED,2019-01-01 00:00:00+00:00,"53,878,159,069,137.0"
15609,OECD members,OED,2018-01-01 00:00:00+00:00,"53,371,534,234,287.0"
16141,OECD members,OED,2020-01-01 00:00:00+00:00,"52,536,127,270,672.0"
15257,High income,HIC,2017-01-01 00:00:00+00:00,"51,570,870,016,900.0"
14459,High income,HIC,2014-01-01 00:00:00+00:00,"51,134,057,169,125.0"
15892,Post-demographic dividend,PST,2019-01-01 00:00:00+00:00,"50,880,064,647,604.0"
15343,OECD members,OED,2017-01-01 00:00:00+00:00,"50,447,226,919,269.0"
15626,Post-demographic dividend,PST,2018-01-01 00:00:00+00:00,"50,385,041,767,150.0"
14545,OECD members,OED,2014-01-01 00:00:00+00:00,"50,278,943,454,196.0"
14193,High income,HIC,2013-01-01 00:00:00+00:00,"50,054,025,962,687.0"
16158,Post-demographic dividend,PST,2020-01-01 00:00:00+00:00,"49,719,390,050,877.0"
13927,High income,HIC,2012-01-01 00:00:00+00:00,"49,446,148,147,436.0"
13661,High income,HIC,2011-01-01 00:00:00+00:00,"49,412,507,535,115.0"
14991,High income,HIC,2016-01-01 00:00:00+00:00,"49,306,277,527,564.0"
14279,OECD members,OED,2013-01-01 00:00:00+00:00,"49,270,437,358,353.0"
13747,OECD members,OED,2011-01-01 00:00:00+00:00,"48,674,651,671,113.0"
14013,OECD members,OED,2012-01-01 00:00:00+00:00,"48,622,412,695,260.0"
15077,OECD members,OED,2016-01-01 00:00:00+00:00,"48,327,404,425,594.0"
14725,High income,HIC,2015-01-01 00:00:00+00:00,"48,273,634,988,452.0"
15360,Post-demographic dividend,PST,2017-01-01 00:00:00+00:00,"47,535,727,573,456.0"
14811,OECD members,OED,2015-01-01 00:00:00+00:00,"47,411,160,772,825.0"

In [25]:
#видалення зі списку рядків які описують не ВВП конкретної країни, а є агрегованими на основі їх показників
remove_list = ["Late-demographic dividend", "OECD members", "Post-demographic dividend", "IDA & IBRD total", "Low & middle income", "Middle income", "IBRD only", "High income", "Upper middle income", "East Asia & Pacific" , "Europe & Central Asia", "East Asia & Pacific (excluding high income)", "East Asia & Pacific (IDA & IBRD countries)"]
df_gdp.drop(df_gdp[df_gdp['country'].isin(remove_list)].index, inplace=True)
df_gdp.sort_values("gdp_value", ascending=False).head(20)

,country,country_code,year,gdp_value
16662,North America,NAC,2022-01-01 00:00:00+00:00,"27,610,090,523,674.0"
16743,United States,USA,2022-01-01 00:00:00+00:00,"25,462,700,000,000.0"
16396,North America,NAC,2021-01-01 00:00:00+00:00,"25,323,694,505,424.0"
16477,United States,USA,2021-01-01 00:00:00+00:00,"23,315,080,560,000.0"
15864,North America,NAC,2019-01-01 00:00:00+00:00,"23,132,124,767,673.0"
16130,North America,NAC,2020-01-01 00:00:00+00:00,"22,714,959,162,303.0"
15598,North America,NAC,2018-01-01 00:00:00+00:00,"22,265,581,227,436.0"
15945,United States,USA,2019-01-01 00:00:00+00:00,"21,380,976,119,000.0"
15332,North America,NAC,2017-01-01 00:00:00+00:00,"21,133,744,509,244.0"
16211,United States,USA,2020-01-01 00:00:00+00:00,"21,060,473,613,000.0"
15679,United States,USA,2018-01-01 00:00:00+00:00,"20,533,057,312,000.0"
15066,North America,NAC,2016-01-01 00:00:00+00:00,"20,230,005,494,907.0"
14800,North America,NAC,2015-01-01 00:00:00+00:00,"19,769,184,098,217.0"
15413,United States,USA,2017-01-01 00:00:00+00:00,"19,477,336,549,000.0"
14534,North America,NAC,2014-01-01 00:00:00+00:00,"19,362,844,040,440.0"
14268,North America,NAC,2013-01-01 00:00:00+00:00,"18,696,254,170,835.0"
15147,United States,USA,2016-01-01 00:00:00+00:00,"18,695,110,842,000.0"
14881,United States,USA,2015-01-01 00:00:00+00:00,"18,206,020,741,000.0"
14002,North America,NAC,2012-01-01 00:00:00+00:00,"18,088,716,899,522.0"
16532,China,CHN,2022-01-01 00:00:00+00:00,"17,963,170,521,080.0"

In [26]:
#підрахунок відсутніх значень
missing_data_gdp = df_gdp.isnull()

for column in missing_data_gdp.columns.values.tolist():
    print(column)
    print(missing_data_gdp[column].value_counts())
    print("")

missing_percent_gdp = df_gdp.isna().mean() * 100
print(missing_percent_gdp)

country
country
False    15876
Name: count, dtype: int64

country_code
country_code
False    15876
Name: count, dtype: int64

year
year
False    15876
Name: count, dtype: int64

gdp_value
gdp_value
False    12489
True      3387
Name: count, dtype: int64

country                0.0
country_code           0.0
year                   0.0
gdp_value      21.33408919
dtype: float64

In [27]:
df_gdp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15876 entries, 0 to 16757
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   country       15876 non-null  object
 1   country_code  15876 non-null  object
 2   year          15876 non-null  datetime64[ns, UTC]
 3   gdp_value     12489 non-null  float64
dtypes: datetime64[ns, UTC](1), float64(1), object(2)
memory usage: 620.2+ KB

In [28]:
# Кількість пропусків по роках (перевірка систематичних)
missing_by_year = df_gdp[df_gdp["gdp_value"].isna()].groupby("year").size()
missing_by_year.head(20)

year
1960-01-01 00:00:00+00:00    133
1961-01-01 00:00:00+00:00    131
1962-01-01 00:00:00+00:00    129
1963-01-01 00:00:00+00:00    129
1964-01-01 00:00:00+00:00    129
1965-01-01 00:00:00+00:00    118
1966-01-01 00:00:00+00:00    116
1967-01-01 00:00:00+00:00    113
1968-01-01 00:00:00+00:00    108
1969-01-01 00:00:00+00:00    108
1970-01-01 00:00:00+00:00     99
1971-01-01 00:00:00+00:00     96
1972-01-01 00:00:00+00:00     96
1973-01-01 00:00:00+00:00     96
1974-01-01 00:00:00+00:00     95
1975-01-01 00:00:00+00:00     93
1976-01-01 00:00:00+00:00     92
1977-01-01 00:00:00+00:00     89
1978-01-01 00:00:00+00:00     90
1979-01-01 00:00:00+00:00     89
dtype: int64

In [29]:
# Показати всі рядки, де gdp_value є NaN
df_gdp[df_gdp["gdp_value"].isna()]

,country,country_code,year,gdp_value
0,Aruba,ABW,1960-01-01 00:00:00+00:00,NaN
4,Angola,AGO,1960-01-01 00:00:00+00:00,NaN
5,Albania,ALB,1960-01-01 00:00:00+00:00,NaN
6,Andorra,AND,1960-01-01 00:00:00+00:00,NaN
7,Arab World,ARB,1960-01-01 00:00:00+00:00,NaN
...,...,...,...,...
16731,Tonga,TON,2022-01-01 00:00:00+00:00,NaN
16746,"Venezuela, RB",VEN,2022-01-01 00:00:00+00:00,NaN
16747,British Virgin Islands,VGB,2022-01-01 00:00:00+00:00,NaN
16748,Virgin Islands (U.S.),VIR,2022-01-01 00:00:00+00:00,NaN
16754,"Yemen, Rep.",YEM,2022-01-01 00:00:00+00:00,NaN

In [30]:
# Тільки топ за пропусками
df_gdp[df_gdp["gdp_value"].isna()].groupby("country").size().sort_values(ascending=False).head(15)

# З відсотком
missing_percent_by_year = (
    df_gdp.groupby("year")["gdp_value"]
    .apply(lambda x: x.isna().mean() * 100)
    .sort_values(ascending=False)
    .round(1)
)
missing_percent_by_year.head(40)

year
1960-01-01 00:00:00+00:00   52.80000000
1961-01-01 00:00:00+00:00   52.00000000
1962-01-01 00:00:00+00:00   51.20000000
1963-01-01 00:00:00+00:00   51.20000000
1964-01-01 00:00:00+00:00   51.20000000
1965-01-01 00:00:00+00:00   46.80000000
1966-01-01 00:00:00+00:00   46.00000000
1967-01-01 00:00:00+00:00   44.80000000
1968-01-01 00:00:00+00:00   42.90000000
1969-01-01 00:00:00+00:00   42.90000000
1970-01-01 00:00:00+00:00   39.30000000
1971-01-01 00:00:00+00:00   38.10000000
1972-01-01 00:00:00+00:00   38.10000000
1973-01-01 00:00:00+00:00   38.10000000
1974-01-01 00:00:00+00:00   37.70000000
1975-01-01 00:00:00+00:00   36.90000000
1976-01-01 00:00:00+00:00   36.50000000
1978-01-01 00:00:00+00:00   35.70000000
1977-01-01 00:00:00+00:00   35.30000000
1979-01-01 00:00:00+00:00   35.30000000
1980-01-01 00:00:00+00:00   29.80000000
1981-01-01 00:00:00+00:00   28.60000000
1982-01-01 00:00:00+00:00   28.20000000
1983-01-01 00:00:00+00:00   27.80000000
1984-01-01 00:00:00+00:00   27.40000000
1985-01-01 00:00:00+00:00   26.60000000
1986-01-01 00:00:00+00:00   25.80000000
1987-01-01 00:00:00+00:00   24.20000000
1988-01-01 00:00:00+00:00   22.20000000
1989-01-01 00:00:00+00:00   22.20000000
1991-01-01 00:00:00+00:00   15.90000000
1990-01-01 00:00:00+00:00   15.90000000
1992-01-01 00:00:00+00:00   15.50000000
1993-01-01 00:00:00+00:00   14.70000000
1994-01-01 00:00:00+00:00   13.90000000
2022-01-01 00:00:00+00:00   13.10000000
1996-01-01 00:00:00+00:00   10.30000000
1997-01-01 00:00:00+00:00   10.30000000
1995-01-01 00:00:00+00:00   10.30000000
1998-01-01 00:00:00+00:00    9.50000000
Name: gdp_value, dtype: float64

In [31]:
#видалення рядків в період з 1960 до 1990 через низьку наявність даних
remove_list = list(range(1960,1990))
df_gdp.drop(df_gdp[df_gdp["year"].dt.year.isin(remove_list)].index, inplace=True)

In [32]:
# Тільки топ за пропусками
df_gdp[df_gdp["gdp_value"].isna()].groupby("country").size().sort_values(ascending=False).head(15)

# З відсотком
missing_percent_by_year = (
    df_gdp.groupby("year")["gdp_value"]
    .apply(lambda x: x.isna().mean() * 100)
    .sort_values(ascending=False)
    .round(1)
)
missing_percent_by_year.head(40)

year
1990-01-01 00:00:00+00:00   15.90000000
1991-01-01 00:00:00+00:00   15.90000000
1992-01-01 00:00:00+00:00   15.50000000
1993-01-01 00:00:00+00:00   14.70000000
1994-01-01 00:00:00+00:00   13.90000000
2022-01-01 00:00:00+00:00   13.10000000
1996-01-01 00:00:00+00:00   10.30000000
1997-01-01 00:00:00+00:00   10.30000000
1995-01-01 00:00:00+00:00   10.30000000
1998-01-01 00:00:00+00:00    9.50000000
1999-01-01 00:00:00+00:00    9.10000000
2000-01-01 00:00:00+00:00    7.50000000
2001-01-01 00:00:00+00:00    6.70000000
2021-01-01 00:00:00+00:00    6.00000000
2002-01-01 00:00:00+00:00    4.80000000
2003-01-01 00:00:00+00:00    4.80000000
2004-01-01 00:00:00+00:00    4.80000000
2005-01-01 00:00:00+00:00    4.80000000
2006-01-01 00:00:00+00:00    4.40000000
2007-01-01 00:00:00+00:00    4.40000000
2008-01-01 00:00:00+00:00    4.00000000
2009-01-01 00:00:00+00:00    4.00000000
2010-01-01 00:00:00+00:00    3.60000000
2019-01-01 00:00:00+00:00    3.60000000
2020-01-01 00:00:00+00:00    3.60000000
2012-01-01 00:00:00+00:00    3.20000000
2015-01-01 00:00:00+00:00    3.20000000
2016-01-01 00:00:00+00:00    3.20000000
2017-01-01 00:00:00+00:00    3.20000000
2018-01-01 00:00:00+00:00    3.20000000
2013-01-01 00:00:00+00:00    2.80000000
2011-01-01 00:00:00+00:00    2.40000000
2014-01-01 00:00:00+00:00    2.40000000
Name: gdp_value, dtype: float64

In [33]:
# Тільки топ за пропусками по країні
df_gdp[df_gdp["gdp_value"].isna()].groupby("country").size().sort_values(ascending=False).head(15)

# З відсотком
missing_percent_by_country = (
    df_gdp.groupby("country")["gdp_value"]
    .apply(lambda x: x.isna().mean() * 100)
    .sort_values(ascending=False)
    .round(1)
)
missing_percent_by_country.head(40)

country
Korea, Dem. People's Rep.   100.00000000
Not classified              100.00000000
Gibraltar                   100.00000000
British Virgin Islands      100.00000000
St. Martin (French part)     93.90000000
South Sudan                  75.80000000
Somalia                      66.70000000
Curacao                      66.70000000
Sint Maarten (Dutch part)    63.60000000
Nauru                        60.60000000
Kosovo                       54.50000000
Channel Islands              51.50000000
Cayman Islands               51.50000000
Virgin Islands (U.S.)        42.40000000
Northern Mariana Islands     42.40000000
Eritrea                      39.40000000
Guam                         39.40000000
Afghanistan                  39.40000000
American Samoa               39.40000000
Turks and Caicos Islands     33.30000000
Sao Tome and Principe        33.30000000
Palau                        33.30000000
Liberia                      30.30000000
Montenegro                   30.30000000
San Marino                   30.30000000
Timor-Leste                  30.30000000
Faroe Islands                27.30000000
Venezuela, RB                24.20000000
Isle of Man                  21.20000000
Croatia                      15.20000000
Israel                       15.20000000
Lithuania                    15.20000000
Slovenia                     15.20000000
Serbia                       15.20000000
Latvia                       15.20000000
Moldova                      15.20000000
Estonia                      15.20000000
Bosnia and Herzegovina       12.10000000
Yemen, Rep.                  12.10000000
West Bank and Gaza           12.10000000
Name: gdp_value, dtype: float64

In [34]:
# Список країн для видалення (взяти з вашого виводу)
countries_to_remove = [
    "Gibraltar",
    "British Virgin Islands",
    "Korea, Dem. People's Rep.",
    "Not classified",
    "St. Martin (French part)",
    "South Sudan",
    "Curacao",
    "Sint Maarten (Dutch part)",
    "Nauru",
    "Kosovo",
    "Cayman Islands",
    "Channel Islands",
    "Northern Mariana Islands",
    "Virgin Islands (U.S.)",
    "Guam",
    "American Samoa",
    "Eritrea",
    "Somalia",
    "Turks and Caicos Islands"
]

# Видалення через drop (змінює оригінальний DataFrame)
df_gdp.drop(
    df_gdp[df_gdp["country"].isin(countries_to_remove)].index,
    inplace=True
)

In [35]:
#заповнення пропусків в gdp_value
# Сортування за країною та роком
df_gdp = df_gdp.sort_values(["country", "country_code", "year"])

# Інтерполяція в межах кожної країни
df_gdp["gdp_value"] = df_gdp.groupby("country")["gdp_value"].transform(
    lambda x: x.interpolate(method="linear", limit_direction="both", limit=3)
)

# Якщо залишилися пропуски на початку/в кінці - заповнити найближчим значенням
df_gdp["gdp_value"] = df_gdp.groupby("country")["gdp_value"].transform(
    lambda x: x.bfill().ffill()
)

#підрахунок відсутніх значень
missing_data_gdp = df_gdp.isnull()

for column in missing_data_gdp.columns.values.tolist():
    print(column)
    print(missing_data_gdp[column].value_counts())
    print("")

missing_percent_gdp = df_gdp.isna().mean() * 100
print(missing_percent_gdp)

df_gdp

country
country
False    7689
Name: count, dtype: int64

country_code
country_code
False    7689
Name: count, dtype: int64

year
year
False    7689
Name: count, dtype: int64

gdp_value
gdp_value
False    7689
Name: count, dtype: int64

country        0.0
country_code   0.0
year           0.0
gdp_value      0.0
dtype: float64

           country country_code                      year        gdp_value
7982   Afghanistan          AFG 1990-01-01 00:00:00+00:00  3,854,235,264.0
8248   Afghanistan          AFG 1991-01-01 00:00:00+00:00  3,854,235,264.0
8514   Afghanistan          AFG 1992-01-01 00:00:00+00:00  3,854,235,264.0
8780   Afghanistan          AFG 1993-01-01 00:00:00+00:00  3,854,235,264.0
9046   Afghanistan          AFG 1994-01-01 00:00:00+00:00  3,854,235,264.0
...            ...          ...                       ...              ...
15693     Zimbabwe          ZWE 2018-01-01 00:00:00+00:00 34,156,069,918.0
15959     Zimbabwe          ZWE 2019-01-01 00:00:00+00:00 21,832,234,926.0
16225     Zimbabwe          ZWE 2020-01-01 00:00:00+00:00 21,509,698,406.0
16491     Zimbabwe          ZWE 2021-01-01 00:00:00+00:00 28,371,238,666.0
16757     Zimbabwe          ZWE 2022-01-01 00:00:00+00:00 20,678,055,598.0

[7689 rows x 4 columns]

In [36]:
# Показати всі рядки, де gdp_value є NaN
df_gdp[df_gdp["gdp_value"].isna()]

Empty DataFrame
Columns: [country, country_code, year, gdp_value]
Index: []

In [37]:
df_gdp.describe(include="all")

,country,country_code,year,gdp_value
count,7689,7689,7689,"7,689.0"
unique,233,233,NaN,NaN
top,Afghanistan,AFG,NaN,NaN
freq,33,33,NaN,NaN
mean,NaN,NaN,2005-12-31 21:05:27.272727296+00:00,"589,317,412,076.9"
min,NaN,NaN,1990-01-01 00:00:00+00:00,"8,824,746.2"
25%,NaN,NaN,1998-01-01 00:00:00+00:00,"4,229,787,234.0"
50%,NaN,NaN,2006-01-01 00:00:00+00:00,"24,728,285,177.0"
75%,NaN,NaN,2014-01-01 00:00:00+00:00,"262,282,344,092.0"
max,NaN,NaN,2022-01-01 00:00:00+00:00,"27,610,090,523,674.0"
std,NaN,NaN,NaN,"2,025,024,365,347.6"

<p>Унікальних назв країн в df_gdp - 233</p>

In [38]:
#перевірка на дублікати
duplicates = df_gdp[df_gdp.duplicated(subset=['country', 'year'], keep=False)]
print("Кількість дублікатів по df_gdp country + year:", len(duplicates))
if len(duplicates) > 0:
    print(duplicates.head())

Кількість дублікатів по df_gdp country + year: 0

In [39]:
#додавання колонки indicator_name
df_gdp['indicator_name'] = 'GDP (2023 US$) by country'

<h2>Обробка датасету df_crypto</h2>

In [40]:
df_crypto.head()

,Date,Open,High,Low,Close,Volume,ticker,name
0,2020-12-23 00:00:00+00:00,594.08734131,617.94927979,564.95886230,588.65533447,64860,STETH-USD,Lido Staked Ether
1,2020-12-24 00:00:00+00:00,588.68646240,613.32812500,551.78460693,611.78747559,53526,STETH-USD,Lido Staked Ether
2,2020-12-25 00:00:00+00:00,611.75903320,626.39721680,600.42053223,626.13623047,45601,STETH-USD,Lido Staked Ether
3,2020-12-26 00:00:00+00:00,626.15002441,642.74627686,610.42718506,627.47247314,10297,STETH-USD,Lido Staked Ether
4,2020-12-27 00:00:00+00:00,627.46545410,707.75122070,617.71978760,682.46716309,90078,STETH-USD,Lido Staked Ether

In [41]:
df_crypto['country'] = 'World'

df_crypto = df_crypto.rename(columns={
    "Date": "date",
    "Open": "open",
    "High": "high",
    "Low": "low",
    "Close": "close",
    "Volume": "volume"
})

df_crypto['date'] = pd.to_datetime(df_crypto['date'])

In [42]:
df_crypto.head()

,date,open,high,low,close,volume,ticker,name,country
0,2020-12-23 00:00:00+00:00,594.08734131,617.94927979,564.95886230,588.65533447,64860,STETH-USD,Lido Staked Ether,World
1,2020-12-24 00:00:00+00:00,588.68646240,613.32812500,551.78460693,611.78747559,53526,STETH-USD,Lido Staked Ether,World
2,2020-12-25 00:00:00+00:00,611.75903320,626.39721680,600.42053223,626.13623047,45601,STETH-USD,Lido Staked Ether,World
3,2020-12-26 00:00:00+00:00,626.15002441,642.74627686,610.42718506,627.47247314,10297,STETH-USD,Lido Staked Ether,World
4,2020-12-27 00:00:00+00:00,627.46545410,707.75122070,617.71978760,682.46716309,90078,STETH-USD,Lido Staked Ether,World

In [43]:
df_crypto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 348828 entries, 0 to 348827
Data columns (total 9 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   date     348828 non-null  datetime64[ns, UTC]
 1   open     346670 non-null  float64
 2   high     346670 non-null  float64
 3   low      346670 non-null  float64
 4   close    348828 non-null  float64
 5   volume   348828 non-null  int64
 6   ticker   348828 non-null  object
 7   name     348828 non-null  object
 8   country  348828 non-null  object
dtypes: datetime64[ns, UTC](1), float64(4), int64(1), object(3)
memory usage: 24.0+ MB

In [44]:
#підрахунок відсутніх значень
missing_data_crypto = df_crypto.isnull()

for column in missing_data_crypto.columns.values.tolist():
    print(column)
    print(missing_data_crypto[column].value_counts())
    print("")

date
date
False    348828
Name: count, dtype: int64

open
open
False    346670
True       2158
Name: count, dtype: int64

high
high
False    346670
True       2158
Name: count, dtype: int64

low
low
False    346670
True       2158
Name: count, dtype: int64

close
close
False    348828
Name: count, dtype: int64

volume
volume
False    348828
Name: count, dtype: int64

ticker
ticker
False    348828
Name: count, dtype: int64

name
name
False    348828
Name: count, dtype: int64

country
country
False    348828
Name: count, dtype: int64

In [45]:
# видалення рядків з порожніми значеннями low, high, open (невелика втрата даних 2158 рядків з 348828)
df_crypto = df_crypto.dropna(subset=["open", "high", "low"])

#повторний підрахунок відсутніх значень
missing_data_crypto = df_crypto.isnull()

for column in missing_data_crypto.columns.values.tolist():
    print(column)
    print(missing_data_crypto[column].value_counts())
    print("")

date
date
False    346670
Name: count, dtype: int64

open
open
False    346670
Name: count, dtype: int64

high
high
False    346670
Name: count, dtype: int64

low
low
False    346670
Name: count, dtype: int64

close
close
False    346670
Name: count, dtype: int64

volume
volume
False    346670
Name: count, dtype: int64

ticker
ticker
False    346670
Name: count, dtype: int64

name
name
False    346670
Name: count, dtype: int64

country
country
False    346670
Name: count, dtype: int64

In [46]:
df_crypto["date"] = pd.to_datetime(df_crypto["date"].astype(str), utc=True)
df_crypto.info()

<class 'pandas.core.frame.DataFrame'>
Index: 346670 entries, 0 to 348827
Data columns (total 9 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   date     346670 non-null  datetime64[ns, UTC]
 1   open     346670 non-null  float64
 2   high     346670 non-null  float64
 3   low      346670 non-null  float64
 4   close    346670 non-null  float64
 5   volume   346670 non-null  int64
 6   ticker   346670 non-null  object
 7   name     346670 non-null  object
 8   country  346670 non-null  object
dtypes: datetime64[ns, UTC](1), float64(4), int64(1), object(3)
memory usage: 26.4+ MB

In [47]:
df_crypto.describe(include="all")

,date,open,high,low,close,volume,ticker,name,country
count,346670,"346,670.0","346,670.0","346,670.0","346,670.0","346,670.0",346670,346670,346670
unique,NaN,NaN,NaN,NaN,NaN,NaN,216,229,1
top,NaN,NaN,NaN,NaN,NaN,NaN,WETH-USD,Litecoin,World
freq,NaN,NaN,NaN,NaN,NaN,NaN,17448,4124,346670
mean,2022-11-02 19:14:48.727608576+00:00,"1,838.3","1,878.2","1,799.3","1,839.4","2,142,819,461.3",NaN,NaN,NaN
min,2014-09-17 00:00:00+00:00,0.0,0.00000000,-1.21755397,0.00000000,0.0,NaN,NaN,NaN
25%,2021-04-27 00:00:00+00:00,0.12660200,0.13350274,0.12037350,0.12652325,"765,728.2",NaN,NaN,NaN
50%,2023-02-16 00:00:00+00:00,1.11952299,1.16721946,1.08014351,1.11939305,"22,449,281.0",NaN,NaN,NaN
75%,2024-08-31 00:00:00+00:00,54.53631401,56.69964886,52.41438961,54.53039265,"201,648,387.8",NaN,NaN,NaN
max,2025-12-31 00:00:00+00:00,"125,813.1","236,493.2","123,230.9","125,813.1","83,252,070,566,791.0",NaN,NaN,NaN
std,NaN,"10,321.9","10,526.3","10,125.8","10,326.6","274,030,090,010.5",NaN,NaN,NaN

<p>Унікальних назв країн в df_crypto - 1(World)</p>

In [48]:
#перевірка на дублікати
duplicates = df_crypto[df_crypto.duplicated(subset=['date', 'ticker'], keep=False)]
print("Кількість дублікатів по df_crypto date + ticker:", len(duplicates))
if len(duplicates) > 0:
    print(duplicates.head())

Кількість дублікатів по df_crypto date + ticker: 48527
                          date       open       high        low      close  \
7785 2018-10-08 00:00:00+00:00 1.00409997 1.00768006 1.00189996 1.00221002
7786 2018-10-09 00:00:00+00:00 1.00426996 1.00832999 1.00003004 1.00686002
7787 2018-10-10 00:00:00+00:00 1.00494003 1.01908004 1.00397003 1.00961995
7788 2018-10-11 00:00:00+00:00 1.00994003 1.03122997 1.00172997 1.00978005
7789 2018-10-12 00:00:00+00:00 1.00861001 1.01871002 1.00114000 1.01271999

       volume    ticker  name country
7785   382900  USDC-USD  USDC   World
7786   108803  USDC-USD  USDC   World
7787   711783  USDC-USD  USDC   World
7788  4177290  USDC-USD  USDC   World
7789  1322240  USDC-USD  USDC   World

In [49]:
#перевірка на дублікати
duplicates = df_crypto[df_crypto.duplicated(subset=['date', 'ticker', "name"], keep=False)]
print("Кількість дублікатів по df_crypto date + ticker + name:", len(duplicates))
if len(duplicates) > 0:
    print(duplicates.head())

Кількість дублікатів по df_crypto date + ticker + name: 0

<h2>Обробка датасету df_inflation</h2>

In [50]:
df_inflation.head()

,country_name,indicator_name,1980,1981,1982,1983,1984,1985,1986,1987,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Afghanistan,Annual average inflation (consumer prices) rate,13.40000000,22.20000000,18.20000000,15.90000000,20.40000000,8.70000000,-2.10000000,18.40000000,...,-0.66000000,4.38000000,4.98000000,0.63000000,2.30000000,5.44000000,5.06000000,13.71000000,9.10000000,NaN
1,Albania,Annual average inflation (consumer prices) rate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.90000000,1.30000000,2.00000000,2.00000000,1.40000000,1.60000000,2.00000000,6.70000000,4.80000000,4.00000000
2,Algeria,Annual average inflation (consumer prices) rate,9.70000000,14.60000000,6.60000000,7.80000000,6.30000000,10.40000000,14.00000000,5.90000000,...,4.80000000,6.40000000,5.60000000,4.30000000,2.00000000,2.40000000,7.20000000,9.30000000,9.00000000,6.80000000
3,Andorra,Annual average inflation (consumer prices) rate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.10000000,-0.40000000,2.60000000,1.00000000,0.50000000,0.10000000,1.70000000,6.20000000,5.20000000,3.50000000
4,Angola,Annual average inflation (consumer prices) rate,46.70000000,1.40000000,1.80000000,1.80000000,1.80000000,1.80000000,1.80000000,1.80000000,...,9.20000000,30.70000000,29.80000000,19.60000000,17.10000000,22.30000000,25.80000000,21.40000000,13.10000000,22.30000000

In [51]:
df_inflation = df_inflation.rename(columns={
    "country_name": "country"
})

#Перетворення wide-формату в long
#melt метод pandas перетворює таблицю з wide у long-формат
df_inflation = df_inflation.melt(
    id_vars=["country", "indicator_name"], #стовпці, які залишаються без змін (не перетворюються в рядки)
    var_name="year", #назва нового стовпця, куди потраплять назви старих стовпців (роки)
    value_name="inflation_value" #назва нового стовпця, куди потраплять значення з тих стовпців-років
)

df_inflation["year"] = pd.to_datetime(df_inflation["year"].astype(str), utc=True)

df_inflation

,country,indicator_name,year,inflation_value
0,Afghanistan,Annual average inflation (consumer prices) rate,1980-01-01 00:00:00+00:00,13.40000000
1,Albania,Annual average inflation (consumer prices) rate,1980-01-01 00:00:00+00:00,NaN
2,Algeria,Annual average inflation (consumer prices) rate,1980-01-01 00:00:00+00:00,9.70000000
3,Andorra,Annual average inflation (consumer prices) rate,1980-01-01 00:00:00+00:00,NaN
4,Angola,Annual average inflation (consumer prices) rate,1980-01-01 00:00:00+00:00,46.70000000
...,...,...,...,...
8815,Vietnam,Annual average inflation (consumer prices) rate,2024-01-01 00:00:00+00:00,3.40000000
8816,West Bank and Gaza,Annual average inflation (consumer prices) rate,2024-01-01 00:00:00+00:00,2.70000000
8817,Yemen,Annual average inflation (consumer prices) rate,2024-01-01 00:00:00+00:00,17.30000000
8818,Zambia,Annual average inflation (consumer prices) rate,2024-01-01 00:00:00+00:00,9.60000000
8819,Zimbabwe,Annual average inflation (consumer prices) rate,2024-01-01 00:00:00+00:00,222.40000000

In [52]:
df_inflation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8820 entries, 0 to 8819
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   country          8820 non-null   object
 1   indicator_name   8820 non-null   object
 2   year             8820 non-null   datetime64[ns, UTC]
 3   inflation_value  7952 non-null   float64
dtypes: datetime64[ns, UTC](1), float64(1), object(2)
memory usage: 275.8+ KB

In [53]:
#підрахунок відсутніх значень
missing_data_inflation = df_inflation.isnull()

for column in missing_data_inflation.columns.values.tolist():
    print(column)
    print(missing_data_inflation[column].value_counts())
    print("")

missing_percent_inflation = df_inflation.isna().mean() * 100
print(missing_percent_inflation)

country
country
False    8820
Name: count, dtype: int64

indicator_name
indicator_name
False    8820
Name: count, dtype: int64

year
year
False    8820
Name: count, dtype: int64

inflation_value
inflation_value
False    7952
True      868
Name: count, dtype: int64

country                  0.0
indicator_name           0.0
year                     0.0
inflation_value   9.84126984
dtype: float64

In [54]:
#заповнення пропусків в inflation_rate
# Сортування за країною та роком
df_inflation = df_inflation.sort_values(["country", "year"])

# Інтерполяція в межах кожної країни
df_inflation["inflation_value"] = df_inflation.groupby("country")["inflation_value"].transform(
    lambda x: x.interpolate(method="linear", limit_direction="both", limit=3)
)

# Якщо залишилися пропуски на початку/в кінці - заповнити найближчим значенням
df_inflation["inflation_value"] = df_inflation.groupby("country")["inflation_value"].transform(
    lambda x: x.bfill().ffill()
)

In [55]:
#підрахунок відсутніх значень
missing_data_inflation = df_inflation.isnull()

for column in missing_data_inflation.columns.values.tolist():
    print(column)
    print(missing_data_inflation[column].value_counts())
    print("")

missing_percent_inflation = df_inflation.isna().mean() * 100
print(missing_percent_inflation)

country
country
False    8820
Name: count, dtype: int64

indicator_name
indicator_name
False    8820
Name: count, dtype: int64

year
year
False    8820
Name: count, dtype: int64

inflation_value
inflation_value
False    8820
Name: count, dtype: int64

country           0.0
indicator_name    0.0
year              0.0
inflation_value   0.0
dtype: float64

In [56]:
df_inflation.describe(include = "all")

,country,indicator_name,year,inflation_value
count,8820,8820,8820,"8,820.0"
unique,196,1,NaN,NaN
top,Afghanistan,Annual average inflation (consumer prices) rate,NaN,NaN
freq,45,8820,NaN,NaN
mean,NaN,NaN,2001-12-31 20:48:00+00:00,63.70089456
min,NaN,NaN,1980-01-01 00:00:00+00:00,-72.70000000
25%,NaN,NaN,1991-01-01 00:00:00+00:00,2.10000000
50%,NaN,NaN,2002-01-01 00:00:00+00:00,4.90000000
75%,NaN,NaN,2013-01-01 00:00:00+00:00,11.20000000
max,NaN,NaN,2024-01-01 00:00:00+00:00,"65,374.1"
std,NaN,NaN,NaN,850.79516034

<p>Унікальних назв країн в df_inflation - 196</p>

In [57]:
#перевірка на дублікати
duplicates = df_inflation[df_inflation.duplicated(subset=['country', 'year'], keep=False)]
print("Кількість дублікатів по df_inflation country + year:", len(duplicates))
if len(duplicates) > 0:
    print(duplicates.head())

Кількість дублікатів по df_inflation country + year: 0

<h2>Обробка датасету df_unemployment</h2>

In [58]:
df_unemployment.head()

,country_name,indicator_name,sex,age_group,age_categories,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Afghanistan,Unemployment rate by sex and age,Female,15-24,Youth,13.34000000,15.97400000,18.57000000,21.13700000,20.64900000,20.15400000,21.22800000,21.64000000,30.56100000,32.20000000,33.33200000
1,Afghanistan,Unemployment rate by sex and age,Female,25+,Adults,8.57600000,9.01400000,9.46300000,9.92000000,11.22300000,12.58700000,14.07900000,14.41500000,23.81800000,26.19200000,28.29800000
2,Afghanistan,Unemployment rate by sex and age,Female,Under 15,Children,10.30600000,11.55200000,12.78900000,14.01700000,14.70600000,15.41800000,16.78300000,17.13400000,26.74600000,29.19300000,30.95600000
3,Afghanistan,Unemployment rate by sex and age,Male,15-24,Youth,9.20600000,11.50200000,13.77200000,16.02700000,15.19900000,14.36100000,14.45200000,15.09900000,16.65500000,18.51200000,19.77000000
4,Afghanistan,Unemployment rate by sex and age,Male,25+,Adults,6.46300000,6.87900000,7.30100000,7.72800000,7.83300000,7.96100000,8.73200000,9.19900000,11.35700000,12.32700000,13.08700000

In [59]:
df_unemployment = df_unemployment.rename(columns={
    "country_name": "country"
})

#Перетворення wide-формату в long
#melt метод pandas перетворює таблицю з wide у long-формат
df_unemployment = df_unemployment.melt(
    id_vars=["country", "indicator_name", "sex", "age_group", "age_categories"], #стовпці, які залишаються без змін (не перетворюються в рядки)
    var_name="year", #назва нового стовпця, куди потраплять назви старих стовпців (роки)
    value_name="unemployment_rate_value" #назва нового стовпця, куди потраплять значення з тих стовпців-років
)

df_unemployment["year"] = pd.to_datetime(df_unemployment["year"].astype(str), utc=True)

df_unemployment

,country,indicator_name,sex,age_group,age_categories,year,unemployment_rate_value
0,Afghanistan,Unemployment rate by sex and age,Female,15-24,Youth,2014-01-01 00:00:00+00:00,13.34000000
1,Afghanistan,Unemployment rate by sex and age,Female,25+,Adults,2014-01-01 00:00:00+00:00,8.57600000
2,Afghanistan,Unemployment rate by sex and age,Female,Under 15,Children,2014-01-01 00:00:00+00:00,10.30600000
3,Afghanistan,Unemployment rate by sex and age,Male,15-24,Youth,2014-01-01 00:00:00+00:00,9.20600000
4,Afghanistan,Unemployment rate by sex and age,Male,25+,Adults,2014-01-01 00:00:00+00:00,6.46300000
...,...,...,...,...,...,...,...
12469,Zimbabwe,Unemployment rate by sex and age,Female,25+,Adults,2024-01-01 00:00:00+00:00,7.52800000
12470,Zimbabwe,Unemployment rate by sex and age,Female,Under 15,Children,2024-01-01 00:00:00+00:00,9.41400000
12471,Zimbabwe,Unemployment rate by sex and age,Male,15-24,Youth,2024-01-01 00:00:00+00:00,13.48500000
12472,Zimbabwe,Unemployment rate by sex and age,Male,25+,Adults,2024-01-01 00:00:00+00:00,6.70300000
12473,Zimbabwe,Unemployment rate by sex and age,Male,Under 15,Children,2024-01-01 00:00:00+00:00,8.63200000

In [60]:
df_unemployment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12474 entries, 0 to 12473
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   country                  12474 non-null  object
 1   indicator_name           12474 non-null  object
 2   sex                      12474 non-null  object
 3   age_group                12474 non-null  object
 4   age_categories           12474 non-null  object
 5   year                     12474 non-null  datetime64[ns, UTC]
 6   unemployment_rate_value  12444 non-null  float64
dtypes: datetime64[ns, UTC](1), float64(1), object(5)
memory usage: 682.3+ KB

In [61]:
#підрахунок відсутніх значень
missing_data_unemployment = df_unemployment.isnull()

for column in missing_data_unemployment.columns.values.tolist():
    print(column)
    print(missing_data_unemployment[column].value_counts())
    print("")

missing_percent_unemployment = df_unemployment.isna().mean() * 100
print(missing_percent_unemployment)

country
country
False    12474
Name: count, dtype: int64

indicator_name
indicator_name
False    12474
Name: count, dtype: int64

sex
sex
False    12474
Name: count, dtype: int64

age_group
age_group
False    12474
Name: count, dtype: int64

age_categories
age_categories
False    12474
Name: count, dtype: int64

year
year
False    12474
Name: count, dtype: int64

unemployment_rate_value
unemployment_rate_value
False    12444
True        30
Name: count, dtype: int64

country                          0.0
indicator_name                   0.0
sex                              0.0
age_group                        0.0
age_categories                   0.0
year                             0.0
unemployment_rate_value   0.24050024
dtype: float64

In [62]:
# видалення рядків з порожніми значеннями unemployment_rate_value (невелика втрата даних 30 рядків з 12474  це 0.24050024%)
df_unemployment = df_unemployment.dropna(subset=["unemployment_rate_value"])

missing_data_unemployment = df_unemployment.isnull()
for column in missing_data_unemployment.columns.values.tolist():
    print(column)
    print(missing_data_unemployment[column].value_counts())
    print("")

country
country
False    12444
Name: count, dtype: int64

indicator_name
indicator_name
False    12444
Name: count, dtype: int64

sex
sex
False    12444
Name: count, dtype: int64

age_group
age_group
False    12444
Name: count, dtype: int64

age_categories
age_categories
False    12444
Name: count, dtype: int64

year
year
False    12444
Name: count, dtype: int64

unemployment_rate_value
unemployment_rate_value
False    12444
Name: count, dtype: int64

In [63]:
df_unemployment.describe(include="all")

,country,indicator_name,sex,age_group,age_categories,year,unemployment_rate_value
count,12444,12444,12444,12444,12444,12444,"12,444.0"
unique,189,1,2,3,3,NaN,NaN
top,Afghanistan,Unemployment rate by sex and age,Female,15-24,Youth,NaN,NaN
freq,66,12444,6222,4148,4148,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,2018-12-28 09:25:51.783992320+00:00,10.82135945
min,NaN,NaN,NaN,NaN,NaN,2014-01-01 00:00:00+00:00,0.02700000
25%,NaN,NaN,NaN,NaN,NaN,2016-01-01 00:00:00+00:00,3.77300000
50%,NaN,NaN,NaN,NaN,NaN,2019-01-01 00:00:00+00:00,7.09250000
75%,NaN,NaN,NaN,NaN,NaN,2022-01-01 00:00:00+00:00,14.05875000
max,NaN,NaN,NaN,NaN,NaN,2024-01-01 00:00:00+00:00,83.99000000
std,NaN,NaN,NaN,NaN,NaN,NaN,10.62062285

<p>Унікальних назв країн в df_unemployment - 189</p>

In [64]:
#перевірка на дублікати 
duplicates = df_unemployment[df_unemployment.duplicated(subset=['country', 'year', "sex", "age_group", "age_categories"], keep=False)]
print("Кількість дублікатів по df_unemployment country + year + sex + age_group + age_categories:", len(duplicates))
if len(duplicates) > 0:
    print(duplicates.head())

Кількість дублікатів по df_unemployment country + year + sex + age_group + age_categories: 0

<h2>Обробка датасету df_real_interest</h2>

In [65]:
df_real_interest.head()

  country_code country_name  year      value
0          ABW        Aruba  1987 6.47543427
1          ABW        Aruba  1988 6.91818004
2          ABW        Aruba  1989 6.26423402
3          ABW        Aruba  1990 4.56664086
4          ABW        Aruba  1991 4.79112522

In [66]:
df_real_interest = df_real_interest.rename(columns={
    "country_name": "country",
    "value": "real_interest_rate"
})

df_real_interest["year"] = pd.to_datetime(df_real_interest["year"].astype(str), utc=True)

df_real_interest

     country_code   country                      year  real_interest_rate
0             ABW     Aruba 1987-01-01 00:00:00+00:00          6.47543427
1             ABW     Aruba 1988-01-01 00:00:00+00:00          6.91818004
2             ABW     Aruba 1989-01-01 00:00:00+00:00          6.26423402
3             ABW     Aruba 1990-01-01 00:00:00+00:00          4.56664086
4             ABW     Aruba 1991-01-01 00:00:00+00:00          4.79112522
...           ...       ...                       ...                 ...
4571          ZWE  Zimbabwe 2017-01-01 00:00:00+00:00          3.74284619
4572          ZWE  Zimbabwe 2018-01-01 00:00:00+00:00        -64.38081686
4573          ZWE  Zimbabwe 2019-01-01 00:00:00+00:00        -64.29515135
4574          ZWE  Zimbabwe 2020-01-01 00:00:00+00:00        -81.13212091
4575          ZWE  Zimbabwe 2021-01-01 00:00:00+00:00        -31.79555083

[4576 rows x 4 columns]

In [67]:
df_real_interest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4576 entries, 0 to 4575
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   country_code        4576 non-null   object
 1   country             4576 non-null   object
 2   year                4576 non-null   datetime64[ns, UTC]
 3   real_interest_rate  4576 non-null   float64
dtypes: datetime64[ns, UTC](1), float64(1), object(2)
memory usage: 143.1+ KB

In [68]:
df_real_interest.describe(include = "all")

,country_code,country,year,real_interest_rate
count,4576,4576,4576,"4,576.0"
unique,148,148,NaN,NaN
top,USA,United States,NaN,NaN
freq,61,61,NaN,NaN
mean,NaN,NaN,2002-05-25 21:47:31.048951040+00:00,6.15848147
min,NaN,NaN,1961-01-01 00:00:00+00:00,-97.69347712
25%,NaN,NaN,1994-01-01 00:00:00+00:00,1.77314394
50%,NaN,NaN,2004-01-01 00:00:00+00:00,5.57925719
75%,NaN,NaN,2012-01-01 00:00:00+00:00,9.82636219
max,NaN,NaN,2021-01-01 00:00:00+00:00,"1,158.0"
std,NaN,NaN,NaN,26.12062952

<p>Унікальних назв країн в df_real_interest - 145</p>

In [69]:
df_real_interest.isna().sum()

country_code          0
country               0
year                  0
real_interest_rate    0
dtype: int64

In [70]:
#перевірка на дублікати 
duplicates = df_real_interest[df_real_interest.duplicated(subset=['country', 'year'], keep=False)]
print("Кількість дублікатів по df_real_interest country + year:", len(duplicates))
if len(duplicates) > 0:
    print(duplicates.head())

Кількість дублікатів по df_real_interest country + year: 0

In [71]:
#додавання колонки indicator_name
df_real_interest['indicator_name'] = 'Real interest rate'

<h2>Уніфікація назв країн</h2>

In [72]:
# Збираємо унікальні країни з усіх джерел
all_countries = pd.concat([
    pd.Series(df_stocks["country"].dropna().unique()),
    pd.Series(df_gdp["country"].dropna().unique()),
    pd.Series(df_inflation["country"].dropna().unique()),
    pd.Series(df_unemployment["country"].dropna().unique()),
    pd.Series(df_real_interest["country"].dropna().unique()),
    pd.Series(df_crypto["country"].dropna().unique())
]).drop_duplicates().sort_values().reset_index(drop=True)

print("Усього унікальних назв країн у всіх джерелах:", len(all_countries))
print(all_countries.to_list())

Усього унікальних назв країн у всіх джерелах: 292
['Afghanistan', 'Africa Eastern and Southern', 'Africa Western and Central', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Arab World', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahamas, The', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Caribbean small states', 'Central African Republic', 'Central Europe and the Baltics', 'Chad', 'Channel Islands', 'Chile', 'China', "China, People's Republic of", 'Colombia', 'Comoros', 'Congo', 'Congo, Dem. Rep.', 'Congo, Dem. Rep. of the', 'Congo, Democratic Republic of the', 'Congo, Rep.', 'Congo, Republic of ', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Czechia', "Côte d'Ivoire", 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Early-demographic dividend', 'Ecuador', 'Egypt', 'Egypt, Arab Rep.', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Euro area', 'Europe & Central Asia (IDA & IBRD countries)', 'Europe & Central Asia (excluding high income)', 'European Union', 'Faroe Islands', 'Fiji', 'Finland', 'Fragile and conflict affected situations', 'France', 'French Polynesia', 'Gabon', 'Gambia', 'Gambia, The', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Greenland', 'Grenada', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Heavily indebted poor countries (HIPC)', 'Honduras', 'Hong Kong SAR', 'Hong Kong SAR, China', 'Hong Kong, China', 'Hungary', 'IDA blend', 'IDA only', 'IDA total', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iran, Islamic Rep.', 'Iran, Islamic Republic of', 'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Ivory Coast', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', "Korea, Democratic People's Republic of", 'Korea, Rep.', 'Korea, Republic of', 'Kosovo', 'Kuwait', 'Kyrgyz Republic', 'Kyrgyzstan', 'Lao P.D.R.', 'Lao PDR', "Lao People's Democratic Republic", 'Latin America & Caribbean', 'Latin America & Caribbean (excluding high income)', 'Latin America & the Caribbean (IDA & IBRD countries)', 'Latvia', 'Least developed countries: UN classification', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Low income', 'Lower middle income', 'Luxembourg', 'Macao SAR', 'Macao SAR, China', 'Macau, China', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia, Fed. States of', 'Micronesia, Fed. Sts.', 'Middle East & North Africa', 'Middle East & North Africa (IDA & IBRD countries)', 'Middle East & North Africa (excluding high income)', 'Moldova', 'Moldova, Republic of', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North America', 'North Macedonia', 'North Macedonia ', 'Norway', 'Oman', 'Other small states', 'Pacific island small states', 'Pakistan', 'Palau', 'Palestinian Territories', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Pre-demographic dividend', 'Puerto Rico', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovakia', 'Slovenia', 'Small states', 'Solomon Islands', 'Somalia', 'South Africa', 'South America', 'South Asia', 'South Asia (IDA & IBRD)', 'South Sudan', 'South Sudan, Republic of', 'Spain', 'Sri Lanka', 'St. Kitts and Nevis', 'St. Lucia', 'St. Vincent and the Grenadines', 'Sub-Saharan Africa', 'Sub-Saharan Africa (IDA & IBRD countries)', 'Sub-Saharan Africa (excluding high income)', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Syrian Arab Republic', 'São Tomé and Príncipe', 'Taiwan Province of China', 'Taiwan, China', 'Tajikistan', 'Tanzania', 'Tanzania, United Republic of', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkiye', 'Turkmenistan', 'Tuvalu', 'Türkiye, Republic of', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'United States Virgin Islands', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Venezuela, Bolivarian Republic of', 'Venezuela, RB', 'Viet Nam', 'Vietnam', 'West Bank and Gaza', 'World', 'Yemen', 'Yemen, Rep.', 'Zambia', 'Zimbabwe', 'canada', 'france', 'germany', 'japan', 'netherlands', 'switzerland', 'usa']

In [73]:
country_map = {
    "Gambia, The": "Gambia",
    "Hong Kong SAR, China": "Hong Kong SAR",
    "Hong Kong, China": "Hong Kong SAR",
    "Korea, Democratic People's Republic of": "The Democratic People's Republic of Korea",
    "Korea, Rep.": "The Republic of Korea",
    "Korea, Republic of": "The Republic of Korea",
    "Kyrgyzstan": "Kyrgyz Republic",
    "Lao P.D.R.": "Lao People's Democratic Republic",
    "Lao PDR": "Lao People's Democratic Republic",
    "Macao SAR, China": "Macao SAR",
    "Macau, China": "Macao SAR",
    "Moldova": "Republic of Moldova",
    "North Macedonia ": "North Macedonia",
    "Slovakia": "Slovak Republic",
    "South Sudan, Republic of": "The Republic of South Sudan",
    "South Sudan": "The Republic of South Sudan",
    "Syria": "Syrian Arab Republic",
    "Taiwan Province of China": "Taiwan",
    "Taiwan, China": "Taiwan",
    "Tanzania": "United Republic of Tanzania",
    "Tanzania, United Republic of": "United Republic of Tanzania",
    "Turkiye": "The Republic of Türkiye",
    "Türkiye, Republic of": "The Republic of Türkiye",
    "Turkey": "The Republic of Türkiye",
    "United States": "United States of America",
    "Venezuela": "Bolivarian Republic of Venezuela",
    "Venezuela, Bolivarian Republic of": "Bolivarian Republic of Venezuela",
    "Venezuela, RB": "Bolivarian Republic of Venezuela",
    "Viet Nam": "Socialist Republic of Vietnam",
    "Vietnam": "Socialist Republic of Vietnam",
    "Yemen": "The Republic of Yemen",
    "Yemen, Rep.": "The Republic of Yemen",
    "canada": "Canada",
    "france": "France",
    "germany": "Germany",
    "japan": "Japan",
    "netherlands": "Netherlands",
    "switzerland": "Switzerland",
    "usa": "United States of America",
    "Bahamas": "The Commonwealth of The Bahamas",
    "Bahamas, The": "The Commonwealth of The Bahamas",
    "China": "People's Republic of China",
    "China, People's Republic of": "People's Republic of China",
    "Congo": "Republic of the Congo",
    "Congo, Dem. Rep.": "Democratic Republic of the Congo",
    "Congo, Dem. Rep. of the": "Democratic Republic of the Congo",
    "Congo, Democratic Republic of the": "Democratic Republic of the Congo",
    "Congo, Rep.": "Republic of the Congo",
    "Congo, Republic of ": "Republic of the Congo",
    "Côte d'Ivoire": "The Republic of Côte d'Ivoire",
    "Cote d'Ivoire": "The Republic of Côte d'Ivoire",
    "Dominican Republic": "Dominican Republic",
    "Egypt": "Arab Republic of Egypt",
    "Egypt, Arab Rep.": "Arab Republic of Egypt",
    "Iran": "Iran, Islamic Republic of",
    "Iran, Islamic Rep.": "Iran, Islamic Republic of",
    "Czechia": "Czech Republic",
    "Moldova, Republic of": "Republic of Moldova",
    "Micronesia, Fed. Sts.": "Micronesia, Fed. States of",
    "St. Kitts and Nevis": "Saint Kitts and Nevis",
    "St. Lucia": "Saint Lucia",
    "St. Vincent and the Grenadines": "Saint Vincent and the Grenadines",
    "Ivory Coast": "The Republic of Côte d'Ivoire",
}

# Застосовуємо мапу до ВСІХ датафреймів
for df in [df_stocks, df_gdp, df_inflation, df_unemployment, df_real_interest]:
    df.loc[:, "country"] = df["country"].replace(country_map)

aggregates_to_remove = [
    "Africa Eastern and Southern",
    "Africa Western and Central",
    "Arab World",
    "Caribbean small states",
    "Central Europe and the Baltics",
    "Early-demographic dividend",
    "Euro area",
    "Europe & Central Asia (IDA & IBRD countries)",
    "Europe & Central Asia (excluding high income)",
    "European Union",
    "Fragile and conflict affected situations",
    "Heavily indebted poor countries (HIPC)",
    "IDA blend",
    "IDA only",
    "IDA total",
    "Latin America & Caribbean",
    "Latin America & Caribbean (excluding high income)",
    "Latin America & the Caribbean (IDA & IBRD countries)",
    "Least developed countries: UN classification",
    "Low income",
    "Lower middle income",
    "Middle East & North Africa",
    "Middle East & North Africa (IDA & IBRD countries)",
    "Middle East & North Africa (excluding high income)",
    "North America",
    "Other small states",
    "Pacific island small states",
    "Pre-demographic dividend",
    "Small states",
    "South America",
    "South Asia",
    "South Asia (IDA & IBRD)",
    "Sub-Saharan Africa",
    "Sub-Saharan Africa (IDA & IBRD countries)",
    "Sub-Saharan Africa (excluding high income)"
]

dfs = [df_stocks, df_gdp, df_inflation, df_unemployment, df_real_interest, df_crypto]

for i in range(len(dfs)):
    dfs[i] = dfs[i][~dfs[i]["country"].isin(aggregates_to_remove)]

df_stocks, df_gdp, df_inflation, df_unemployment, df_real_interest, df_crypto = dfs



# Перевіряємо, чи зменшилася кількість унікальних країн
print("Після мапінгу унікальних країн у stocks:", df_stocks["country"].nunique())
print("Після мапінгу унікальних країн у gdp:", df_gdp["country"].nunique())
print("Після мапінгу унікальних країн у inflation:", df_inflation["country"].nunique())
print("Після мапінгу унікальних країн у unemployment:", df_unemployment["country"].nunique())
print("Після мапінгу унікальних країн у real_interest:", df_real_interest["country"].nunique())

Після мапінгу унікальних країн у stocks: 7
Після мапінгу унікальних країн у gdp: 199
Після мапінгу унікальних країн у inflation: 196
Після мапінгу унікальних країн у unemployment: 188
Після мапінгу унікальних країн у real_interest: 148

In [74]:
# Збираємо унікальні країни з усіх джерел
all_countries = pd.concat([
    pd.Series(df_stocks["country"].dropna().unique()),
    pd.Series(df_gdp["country"].dropna().unique()),
    pd.Series(df_inflation["country"].dropna().unique()),
    pd.Series(df_unemployment["country"].dropna().unique()),
    pd.Series(df_real_interest["country"].dropna().unique()),
    pd.Series(df_crypto["country"].dropna().unique())
]).drop_duplicates().sort_values().reset_index(drop=True)

print("Усього унікальних назв країн у всіх джерелах:", len(all_countries))
print(all_countries.to_list())

Усього унікальних назв країн у всіх джерелах: 212
['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Arab Republic of Egypt', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivarian Republic of Venezuela', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Channel Islands', 'Chile', 'Colombia', 'Comoros', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Democratic Republic of the Congo', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Faroe Islands', 'Fiji', 'Finland', 'France', 'French Polynesia', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Greenland', 'Grenada', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong SAR', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran, Islamic Republic of', 'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait', 'Kyrgyz Republic', "Lao People's Democratic Republic", 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macao SAR', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia, Fed. States of', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Palestinian Territories', 'Panama', 'Papua New Guinea', 'Paraguay', "People's Republic of China", 'Peru', 'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'Republic of Moldova', 'Republic of the Congo', 'Romania', 'Russian Federation', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia', 'Socialist Republic of Vietnam', 'Solomon Islands', 'Somalia', 'South Africa', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syrian Arab Republic', 'São Tomé and Príncipe', 'Taiwan', 'Tajikistan', 'Thailand', 'The Commonwealth of The Bahamas', "The Democratic People's Republic of Korea", "The Republic of Côte d'Ivoire", 'The Republic of Korea', 'The Republic of South Sudan', 'The Republic of Türkiye', 'The Republic of Yemen', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United Republic of Tanzania', 'United States Virgin Islands', 'United States of America', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'West Bank and Gaza', 'World', 'Zambia', 'Zimbabwe']

In [75]:
# Перевірка кожного датафрейму окремо на порожні значення
print("Stocks:", df_stocks[df_stocks["country"] == ""])
print("GDP:", df_gdp[df_gdp["country"] == ""])
print("Inflation:", df_inflation[df_inflation["country"] == ""])
print("Unemployment:", df_unemployment[df_unemployment["country"] == ""])
print("Real interest:", df_real_interest[df_real_interest["country"] == ""])
print("Crypto:", df_crypto[df_crypto["country"] == ""])

Stocks: Empty DataFrame
Columns: [date, open, high, low, close, volume, brand_name, ticker, industry_tag, country, dividends, stock_splits, daily_return]
Index: []
GDP: Empty DataFrame
Columns: [country, country_code, year, gdp_value, indicator_name]
Index: []
Inflation: Empty DataFrame
Columns: [country, indicator_name, year, inflation_value]
Index: []
Unemployment: Empty DataFrame
Columns: [country, indicator_name, sex, age_group, age_categories, year, unemployment_rate_value]
Index: []
Real interest: Empty DataFrame
Columns: [country_code, country, year, real_interest_rate, indicator_name]
Index: []
Crypto: Empty DataFrame
Columns: [date, open, high, low, close, volume, ticker, name, country]
Index: []

<h2>Додавання інших колонок та формування фінальних датасетів</h2>

In [76]:
df_stocks["asset_type"] = "Stock"
df_crypto["asset_type"] = "Crypto"

In [77]:
#об'єднання stocks і crypto в один датафрейм
df_assets = pd.concat([df_stocks, df_crypto], ignore_index=True)

In [78]:
# очищення від дублікатів
print("Перед видаленняя дублікатів к-ть рядків: ", len(df_assets))

df_assets = df_assets.sort_values(['date', 'ticker', 'volume'], ascending=[True, True, False])

df_assets = df_assets.drop_duplicates(subset=['date', 'ticker'], keep='first')   # залишаємо рядок з найбільшим volume

print("Після видалення дублікатів залишилось рядків: ", len(df_assets))

Перед видаленняя дублікатів к-ть рядків:  653115
Після видалення дублікатів залишилось рядків:  622262

In [79]:
#підрахунок відсутніх значень
missing_data_assets = df_assets.isnull()

for column in missing_data_assets.columns.values.tolist():
    print(column)
    print(missing_data_assets[column].value_counts())
    print("")

missing_percent_assets = df_assets.isna().mean() * 100
print(missing_percent_assets)

date
date
False    622262
Name: count, dtype: int64

open
open
False    622262
Name: count, dtype: int64

high
high
False    622262
Name: count, dtype: int64

low
low
False    622262
Name: count, dtype: int64

close
close
False    622262
Name: count, dtype: int64

volume
volume
False    622262
Name: count, dtype: int64

brand_name
brand_name
True     315817
False    306445
Name: count, dtype: int64

ticker
ticker
False    622262
Name: count, dtype: int64

industry_tag
industry_tag
True     315817
False    306445
Name: count, dtype: int64

country
country
False    622262
Name: count, dtype: int64

dividends
dividends
True     315817
False    306445
Name: count, dtype: int64

stock_splits
stock_splits
True     315817
False    306445
Name: count, dtype: int64

daily_return
daily_return
True     315879
False    306383
Name: count, dtype: int64

asset_type
asset_type
False    622262
Name: count, dtype: int64

name
name
False    315817
True     306445
Name: count, dtype: int64

date                   0.0
open                   0.0
high                   0.0
low                    0.0
close                  0.0
volume                 0.0
brand_name     50.75305900
ticker                 0.0
industry_tag   50.75305900
country                0.0
dividends      50.75305900
stock_splits   50.75305900
daily_return   50.76302265
asset_type             0.0
name           49.24694100
dtype: float64

<p>Для фінансових активів (акції та криптовалюти) дані об'єднано в єдиний датафрейм df_assets за допомогою pd.concat, оскільки обидва джерела мають спільні ключові поля (date, open/high/low/close, volume, ticker, country). Колонки, специфічні для одного джерела (brand_name, industry_tag, dividends, stock_splits для акцій; name для крипто), заповнено значенням "N/A" або 0.0. Відсутність даних у специфічних колонках є очікуваною і не впливає на аналіз, оскільки вони не є обов'язковими для розрахунку дохідності.</p>

In [80]:
df_assets = df_assets.sort_values("date", ignore_index=True)
df_assets.head()

,date,open,high,low,close,volume,brand_name,ticker,industry_tag,country,dividends,stock_splits,daily_return,asset_type,name
0,2000-01-03 05:00:00+00:00,0.79479960,0.85258569,0.77064283,0.84832299,"535,796,800.0",apple,AAPL,technology,United States of America,0.0,0.0,NaN,Stock,NaN
1,2000-01-03 05:00:00+00:00,2.64790623,2.65988770,2.61196180,2.63292956,"76,000.0",logitech,LOGI,technology,Switzerland,0.0,0.0,NaN,Stock,NaN
2,2000-01-03 05:00:00+00:00,9.65398122,9.76580339,9.35578819,9.46761036,"3,277,800.0",southwest airlines,LUV,aviation,United States of America,0.0,0.0,NaN,Stock,NaN
3,2000-01-03 05:00:00+00:00,11.82669488,11.85011344,11.40514933,11.42856789,"2,506,717.0",marriott,MAR,hospitality,United States of America,0.0,0.0,NaN,Stock,NaN
4,2000-01-03 05:00:00+00:00,22.36106925,22.43105695,21.80116767,22.18610001,"4,520,600.0",mcdonald's,MCD,food,United States of America,0.0,0.0,NaN,Stock,NaN

In [81]:
#перевірка на дублікати 
duplicates = df_assets[df_assets.duplicated(subset=['date', 'ticker', "name"], keep=False)]
print("Кількість дублікатів по df_assets date + ticker + name:", len(duplicates))
if len(duplicates) > 0:
    print(duplicates.head())

Кількість дублікатів по df_assets date + ticker + name: 0

In [83]:
#збереження чистих файлів

path = r"C:/Users/stepa/Desktop/АДІС/KP_ADIS_Macroeconomic_analysis/ADIS_Project_clean_datasets/"

#збереження чистих файлів
df_assets.to_csv(path + "assets_clean.csv", index=False)
df_gdp.to_csv(path + "gdp_clean.csv", index=False)
df_inflation.to_csv(path + "inflation_clean.csv", index=False)
df_unemployment.to_csv(path + "unemployment_clean.csv", index=False)
df_real_interest.to_csv(path + "real_interest_clean.csv", index=False)

In [84]:
#Перевірка чи правильно збереглось
# Зчитати збережені файли
df_assets_check = pd.read_csv(path + "assets_clean.csv", sep = ",", encoding = "cp1252")
df_gdp_check = pd.read_csv(path + "gdp_clean.csv", sep = ",", encoding = "cp1252")
df_inflation_check = pd.read_csv(path + "inflation_clean.csv", sep = ",", encoding = "cp1252")
df_unemployment_check = pd.read_csv(path + "unemployment_clean.csv", sep = ",", encoding = "cp1252")
df_real_interest_check = pd.read_csv(path + "real_interest_clean.csv", sep = ",", encoding = "cp1252")



# Перевірити розміри (кількість рядків і колонок)
print("ПЕРЕВІРКА РОЗМІРІВ")
print(f"assets: оригінал {df_assets.shape} -> зчитано {df_assets_check.shape}")
print(f"gdp: оригінал {df_gdp.shape} -> зчитано {df_gdp_check.shape}")
print(f"inflation: оригінал {df_inflation.shape} -> зчитано {df_inflation_check.shape}")
print(f"unemployment: оригінал {df_unemployment.shape} -> зчитано {df_unemployment_check.shape}")
print(f"real_interest: оригінал {df_real_interest.shape} -> зчитано {df_real_interest_check.shape}")

print("\nПЕРШІ 5 РЯДКІВ ЗБЕРЕЖЕНИХ ФАЙЛІВ")
print("\nassets_clean.csv:")
print(df_assets_check.head())

print("\ngdp_clean.csv:")
print(df_gdp_check.head())

print("\ninflation_clean.csv:")
print(df_inflation_check.head())

print("\nunemployment_clean.csv:")
print(df_unemployment_check.head())

print("\nreal_interest_clean.csv:")
print(df_real_interest_check.head())

C:\Users\stepa\AppData\Local\Temp\ipykernel_8988\3264180978.py:3: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df_assets_check = pd.read_csv(path + "assets_clean.csv", sep = ",", encoding = "cp1252")

ПЕРЕВІРКА РОЗМІРІВ
assets: оригінал (622262, 15) -> зчитано (622262, 15)
gdp: оригінал (6567, 5) -> зчитано (6567, 5)
inflation: оригінал (8820, 4) -> зчитано (8820, 4)
unemployment: оригінал (12378, 7) -> зчитано (12378, 7)
real_interest: оригінал (4576, 5) -> зчитано (4576, 5)

ПЕРШІ 5 РЯДКІВ ЗБЕРЕЖЕНИХ ФАЙЛІВ

assets_clean.csv:
                        date        open        high         low       close  \
0  2000-01-03 05:00:00+00:00  0.79479960  0.85258569  0.77064283  0.84832299
1  2000-01-03 05:00:00+00:00  2.64790623  2.65988770  2.61196180  2.63292956
2  2000-01-03 05:00:00+00:00  9.65398122  9.76580339  9.35578819  9.46761036
3  2000-01-03 05:00:00+00:00 11.82669488 11.85011344 11.40514933 11.42856789
4  2000-01-03 05:00:00+00:00 22.36106925 22.43105695 21.80116767 22.18610001

         volume          brand_name ticker industry_tag  \
0 535,796,800.0               apple   AAPL   technology
1      76,000.0            logitech   LOGI   technology
2   3,277,800.0  southwest airlines    LUV     aviation
3   2,506,717.0            marriott    MAR  hospitality
4   4,520,600.0          mcdonald's    MCD         food

                    country  dividends  stock_splits  daily_return asset_type  \
0  United States of America        0.0           0.0           NaN      Stock
1               Switzerland        0.0           0.0           NaN      Stock
2  United States of America        0.0           0.0           NaN      Stock
3  United States of America        0.0           0.0           NaN      Stock
4  United States of America        0.0           0.0           NaN      Stock

  name
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN

gdp_clean.csv:
       country country_code                       year       gdp_value  \
0  Afghanistan          AFG  1990-01-01 00:00:00+00:00 3,854,235,264.0
1  Afghanistan          AFG  1991-01-01 00:00:00+00:00 3,854,235,264.0
2  Afghanistan          AFG  1992-01-01 00:00:00+00:00 3,854,235,264.0
3  Afghanistan          AFG  1993-01-01 00:00:00+00:00 3,854,235,264.0
4  Afghanistan          AFG  1994-01-01 00:00:00+00:00 3,854,235,264.0

              indicator_name
0  GDP (2023 US$) by country
1  GDP (2023 US$) by country
2  GDP (2023 US$) by country
3  GDP (2023 US$) by country
4  GDP (2023 US$) by country

inflation_clean.csv:
       country                                   indicator_name  \
0  Afghanistan  Annual average inflation (consumer prices) rate
1  Afghanistan  Annual average inflation (consumer prices) rate
2  Afghanistan  Annual average inflation (consumer prices) rate
3  Afghanistan  Annual average inflation (consumer prices) rate
4  Afghanistan  Annual average inflation (consumer prices) rate

                        year  inflation_value
0  1980-01-01 00:00:00+00:00      13.40000000
1  1981-01-01 00:00:00+00:00      22.20000000
2  1982-01-01 00:00:00+00:00      18.20000000
3  1983-01-01 00:00:00+00:00      15.90000000
4  1984-01-01 00:00:00+00:00      20.40000000

unemployment_clean.csv:
       country                    indicator_name     sex age_group  \
0  Afghanistan  Unemployment rate by sex and age  Female     15-24
1  Afghanistan  Unemployment rate by sex and age  Female       25+
2  Afghanistan  Unemployment rate by sex and age  Female  Under 15
3  Afghanistan  Unemployment rate by sex and age    Male     15-24
4  Afghanistan  Unemployment rate by sex and age    Male       25+

  age_categories                       year  unemployment_rate_value
0          Youth  2014-01-01 00:00:00+00:00              13.34000000
1         Adults  2014-01-01 00:00:00+00:00               8.57600000
2       Children  2014-01-01 00:00:00+00:00              10.30600000
3          Youth  2014-01-01 00:00:00+00:00               9.20600000
4         Adults  2014-01-01 00:00:00+00:00               6.46300000

real_interest_clean.csv:
  country_code country                       year  real_interest_rate  \
0          ABW   Aruba  1987-01-01 00:00:00+00:00          6.47543427
1          ABW   Aruba  1988-01-01 00:00:00+00:00          6.91818004
2          ABW   Aruba  1989-01-01 00:00:00+00:00          6.26423402
3          ABW   Aruba  1990-01-01 00:00:00+00:00          4.56664086
4          ABW   Aruba  1991-01-01 00:00:00+00:00          4.79112522

       indicator_name
0  Real interest rate
1  Real interest rate
2  Real interest rate
3  Real interest rate
4  Real interest rate

<p>Під час зчитування файлу assets_clean.csv pandas видає попередження DtypeWarning через змішані типи в колонці name (заповнено "N/A" для акцій). Це не впливає на цілісність даних і структуру сховища.</p>

In [85]:
df_assets_check.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 622262 entries, 0 to 622261
Data columns (total 15 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   date          622262 non-null  object
 1   open          622262 non-null  float64
 2   high          622262 non-null  float64
 3   low           622262 non-null  float64
 4   close         622262 non-null  float64
 5   volume        622262 non-null  float64
 6   brand_name    306445 non-null  object
 7   ticker        622262 non-null  object
 8   industry_tag  306445 non-null  object
 9   country       622262 non-null  object
 10  dividends     306445 non-null  float64
 11  stock_splits  306445 non-null  float64
 12  daily_return  306383 non-null  float64
 13  asset_type    622262 non-null  object
 14  name          315817 non-null  object
dtypes: float64(8), object(7)
memory usage: 71.2+ MB

<h2>Виконала студентка групи ІП-з41 Степанова Марія</h2>